# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/uploads/default'
                lock: 0
                skip_links: false
                permissions:
                    file:
                        public: 0o744
                        private: 0o700
                    dir:
                        public: 0o755
                        private: 0o700